title: <p align="center">  Haorui Zhang  </p>
logo: "/images/profile.png?raw=true" 
description:
  <p align="center">
  <a href="https://www.linkedin.com/in/haorui-z-980507181/">LinkedIn</a> |
  <a href="https://scholar.google.com/citations?user=6M8zqjUAAAAJ&hl=en">Google Scholar</a> |
  <a href="hz3296@nyu.edu">email</a>
  <a href="https://github.com/haorui-zhang/">GitHub</a>
  </p>
  
  I am pursing a MS degree in Data Science at Center of Data Science, New York University. 
  <br><br>
  I was graduated from Wake Forest University with a double major in Finance and Statistics
  <br><br>
  I have experiences with all kinds of Data Science project, including biology, history, archeology, finance, mathematics, etc
  </p>
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
